---
version: '3.7'
networks:
  default:
    name: traefik-public

services:
  traefik:
    image: traefik:v2.9.1
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    security_opt:
      - seccomp:unconfined

# vim: set sw=2 et:
