---
# traefik.yml

# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.teleport.local`)"

# API and dashboard configuration
api:
  insecure: true

# vim: set sw=2 et:
